### ISSUE TITLE
Packet 32

### ISSUE THREAD

**Issue by Gjum** [DnAp/Agar.io-Reverse-Engineering#13]
After splitting, packet 32 informs the client which cell belongs to the player.
See [my working implementation](https://github.com/Gjum/pyAgar.io/blob/master/client.py#L329-337) for reference.

**Comment by TheZ3ro** [comment]
What do you mean with this? I don't understand well.

**Comment by Hellsing** [comment]
Pretty easy to understand what he wants to tell you: The readme.md shows wrong information about packet 32:

"32: creates new bucket
    probably your own id for bucket. called for first time only when started"

**Comment by TheZ3ro** [comment]
Now it's more clear, I will fix it ASAP and pull a request

**Comment by Gjum** [comment]
Sorry for being a bit unclear, it was a bit late that night ^^
Yeah, it's about the description in the readme. It says there:

> probably your own id for bucket. called for first time only when started

Actually it's sent every time you split or respawn.
Your own cells' positions/sizes are sent like the other cells in the world update packet.
Joining your cells also is done in the world update packet, the same way as dying cells.

**Comment by TheZ3ro** [comment]
Fixed in #14
