### ISSUE TITLE
Have a problem with starting

### ISSUE THREAD

**Issue by ks-s-a** [DnAp/Agar.io-Reverse-Engineering#2]
When i press the play button, take a message: 

"Connecting
If you cannot connect to the servers, check if you have some anti virus or firewall blocking the connection."

On clear game version all ok.

**Comment by ks-s-a** [comment]
Hmm.. I try to use 80 port and all ok. Problem only with 8080 port.

**Comment by DnAp** [comment]
I created php proxy to other domain and your case
