### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by rean1m5** [DnAp/Agar.io-Reverse-Engineering#3]
Постоянно выскакивают такие ошибки и не коннектится ни к одному серверу:

main_out.js:197 WebSocket connection to 'ws://109.237.27.68:443/' failed: Error during WebSocket handshake: Unexpected response code: 400
main_out.js:203 socket error
main_out.js:217 socket close

**Comment by Uvadzucumi** [comment]
use nginx web server. in my apache2 same problem with WebSoket ssh connection.

**Comment by DnAp** [comment]
Use domain localhost or agar.io. Until just so(
---- On Russian:
Используйте домен localhost или agar.io, пока подругому не работает(

**Comment by rean1m5** [comment]
Got it! now all fine - thanks :)
