### ISSUE TITLE
close() function name

### ISSUE THREAD

**Issue by jazzpi** [DnAp/Agar.io-Reverse-Engineering#4]
Fist of all, thanks for the great work on this! I tried reverse engineering this myself, but I got stuck.

Now, why did you call the `close` function `close`? It looks to me like it simply sends the nickname to the server, since the `result` variable is the value of the nickname input and it sends a Null byte and then all characters from `result` (UTF-16 encoded?).

Am I missing something here?

**Comment by DnAp** [comment]
It's simple.
For main work i used jsnice.org. It service based machine learning and it have fail=) I don't rename all functions and variables.
Thanks. I rename function to sendNickname.
If you found new fail, please sent pull request.

**Comment by jazzpi** [comment]
Oh, I didn't know about jsnice. I'll have to remember that in the future!
