### ISSUE TITLE
Open as localhost or agar.io

### ISSUE THREAD

**Issue by DeastinY** [DnAp/Agar.io-Reverse-Engineering#6]
Hey,

First of all great work, secondly I don't understang exactly what you want to say with the last information.
So I dropped the files to my server and made them accessible via someurl.com.
How could I possibly do either localhost (server is console only) or agar.io (domain is owned by creator ofc)

Kind regards

**Comment by destroy-everything** [comment]
Use a hosts file
http://en.wikipedia.org/wiki/Hosts_%28file%29

**Comment by elraro** [comment]
Hi! i have the same question that @DeastinY . I dont know how can i use the hosts file and redirect from agar.io to my subdomain :/

**Comment by jazzpi** [comment]
I think the idea is that you run a local server on your machine (i.e. [XAMPP](https://www.apachefriends.org/index.html) or similar) and then access the files through that server (i.e. on your `localhost` address).

Since this is all static content however, I think it would be sufficient to simply drop all files into one folder, then open the `index.html` with your browser.

**Comment by i9w** [comment]
Why it doesn't work with grease monkey

**Comment by DnAp** [comment]
i2w, it is my decision.

**Comment by i9w** [comment]
u wut m8, lol it's i9w, 2nd ur bot sucks fr.

**Comment by jazzpi** [comment]
What a nice guy. You also missed the point of this, this isn't a bot.

**Comment by i9w** [comment]
Actually it's intended to work as a "bot", otherwise in full terminology a "web application api". That surely doesn't deliver on it's promise, say "reverse-engineering".

**Comment by jazzpi** [comment]
A web application API is not a bot. I suggest you do some reading about bots. http://en.wikipedia.org/wiki/Internet_bot

**Comment by i9w** [comment]
If you don't regard it as a bot, then you should remove the term "reverse-engineering", as such task is intended to "trick" the application into doing something it's not supposed to. Or as the Russians call it "creating a medicine" or by western term "a crack" and that's by "reverse-engineering the application". 

The outcome of your so-called "bot" can be achieved by simply inspecting elements from the browser.

**Comment by jazzpi** [comment]
http://en.wikipedia.org/wiki/Reverse_engineering
You can use reverse engineering to write a bot. Reverse engineering  isn't writing a bot.

**Comment by i9w** [comment]
I suppose you're just Copy/pasting irrelevant links because you don't know what the hell you're talking about LOL.

**Comment by TheZ3ro** [comment]
Just stop this flamewar.

This isn't a bot, only a project for studing how agar.io works.
But obviously it can be used as a "hack" ("bot" is an AI that play itself on agar.io)

If you want some greasemonkey hack, search for them on google ;)

**Comment by destroy-everything** [comment]
This guy is fuc%ed
