### ISSUE TITLE
Better ennemy hack calculation

### ISSUE THREAD

**Issue by te-deum** [DnAp/Agar.io-Reverse-Engineering#7]
Hello,

I really appreciate your project and use it to have more informations while playing Agar :-)
I just notice that the calcul done for mass comparaison is not optimized and is not correct.

Around line 971, you have :
```javascript
}else if(isTypesHack && !this.isVirus){
	if (this.size < minMass * 0.9 / 2) {
		this.color = '#57FF07';
	} else if (this.size < minMass * 0.9) {
		this.color = '#07FFB0';
	} else if (this.size * 0.9 > minMass) {
		this.color = '#FF3107';
	} else {
		this.color = '#4106FF';
	}
}
```

You should have that :
```javascript
}else if(isTypesHack && !this.isVirus && this.size > 14){
	if (this.size * 0.9 > minMass) {
		this.color = '#FF3107';
	} else if (this.size < (minMass / 1.414213562) * 0.9) {
		this.color = '#57FF07';
	} else if (this.size < minMass * 0.9) {
		this.color = '#07FFB0';
	} else {
		this.color = '#4106FF';
	}
}
```
In fact, there is more Red than Green. And when there will be more Green, you are big and slower.
minMass is the square root of the mass. We must divide by the square root of 2, not 2 directly.
And we do not compare mass less than 14. It correspond to dots on the board.

Hope this would help to have better hack :)
Regards.

**Comment by DnAp** [comment]
Thanks, commit it is.
